### ISSUE TITLE
User-specified output files

### ISSUE THREAD

**Issue by fgvieira** [Adrian-Cantu/pprinseqc#4] opened 2018-06-11 13:37 UTC
Dear,

I've been looking for this for a while, since I quite like PRINSEQ but it is slow and sometime uses a lot of memory (apart from not using gzip files natively). However, I do have a small request, if it would be possible to specify the output file names.

Right now, you can use `out_name` but that is just a prefix. Would it be possible for the user to manually specify all potential 6 output file names? I know that it is a lot of names and most people will just use the prefix, but to include in pipelines it is quite nice to be able to specify all of them.

Ideally, I'd say that default behaviour stays as is. If any of the 6 output files names is specified, it replaces the prefix (if not specified, prefix is used). If two files have the same name, it output both to the same file (for example `<string>_single_out_R1` and `<string>_single_out_R2`; or `<string>_bad_out_R1` and `<string>_bad_out_R2`).

cheers,

**Comment by Adrian-Cantu** [comment] 2018-06-12 22:15
Hi,
I made those changes in the develop branch [https://github.com/Adrian-Cantu/PRINSEQ-plus-plus/tree/develop](https://github.com/Adrian-Cantu/PRINSEQ-plus-plus/tree/develop). you can clone and compile from there, or use this file. [prinseq-plus-plus-1.1_devel.tar.gz](https://github.com/Adrian-Cantu/PRINSEQ-plus-plus/files/2095980/prinseq-plus-plus-1.1_devel.tar.gz)

Regarding sending two outputs to the same file, I'm not sure if it is thread-safe with the current design, but I implemented it anyway. Is this something you really need? I will do some more testing and push to master when I'm sure it works.

Regards

**Comment by fgvieira** [comment] 2018-06-13 11:55
Hi Adrian,

super, that sounds great!

About sending the two outputs into the same file, no it is not that important; just convenient. :)
I usually analyze paired-end data and, before the prinseq step, I usually remove adapters and do a merging/collapsing step (in case the two reads overlap). that means that I end up having, for each sample, paired end reads plus the collapsed reads (which are basically single end).

So, when I run prinseq, I have to actually run it twice (for SE and PE), and then merge the three single-end-like files (_single_out_R1, _single_out_R2, and  _good_out) into one.
So, I thought that it could be easier to have them all in one file since they will all be mapped together, no?

best,

**Comment by fgvieira** [comment] 2018-06-14 11:08
Hi Adrian,

I tried compiling the devel version but I am getting an error:
```
g++ -std=gnu++11 -g -O2 -pthread   -c -o main.o main.cpp
g++ -std=gnu++11 -g -O2 -pthread   -c -o reads.o reads.cpp
g++ -std=gnu++11 -g -O2 -pthread   -c -o verbose.o verbose.cpp
verbose.cpp: In member function ‘void verbose::accumulate()’:
verbose.cpp:34:19: error: ‘accumulate’ is not a member of ‘std’
     total_min_len=std::accumulate((*min_len).begin(), (*min_len).end(), 0);
                   ^
verbose.cpp:35:19: error: ‘accumulate’ is not a member of ‘std’
     total_max_len=std::accumulate((*max_len).begin(), (*max_len).end(), 0);
                   ^
verbose.cpp:36:18: error: ‘accumulate’ is not a member of ‘std’
     total_min_cg=std::accumulate((*min_cg).begin(), (*min_cg).end(), 0);
                  ^
verbose.cpp:37:18: error: ‘accumulate’ is not a member of ‘std’
     total_max_cg=std::accumulate((*max_cg).begin(), (*max_cg).end(), 0);
                  ^
verbose.cpp:38:26: error: ‘accumulate’ is not a member of ‘std’
     total_min_qual_score=std::accumulate((*min_qual_score).begin(), (*min_qual_score).end(), 0);
                          ^
verbose.cpp:39:25: error: ‘accumulate’ is not a member of ‘std’
     total_min_qual_mean=std::accumulate((*min_qual_mean).begin(),(*min_qual_mean).end(),0);
                         ^
verbose.cpp:40:20: error: ‘accumulate’ is not a member of ‘std’
     total_ns_max_n=std::accumulate((*ns_max_n).begin(), (*ns_max_n).end(), 0);
                    ^
verbose.cpp:41:19: error: ‘accumulate’ is not a member of ‘std’
     total_noiupac=std::accumulate((*noiupac).begin(), (*noiupac).end(), 0);
                   ^
verbose.cpp:42:17: error: ‘accumulate’ is not a member of ‘std’
     total_derep=std::accumulate((*derep).begin(), (*derep).end(), 0);
                 ^
verbose.cpp:43:22: error: ‘accumulate’ is not a member of ‘std’
     total_lc_entropy=std::accumulate((*lc_entropy).begin(),(*lc_entropy).end(),0);
                      ^
verbose.cpp:45:19: error: ‘accumulate’ is not a member of ‘std’
     total_lc_dust=std::accumulate((*lc_dust).begin(), (*lc_dust).end(), 0);
                   ^
verbose.cpp:46:26: error: ‘accumulate’ is not a member of ‘std’
     total_trim_tail_left=std::accumulate((*trim_tail_left).begin(), (*trim_tail_left).end(), 0);
                          ^
verbose.cpp:47:27: error: ‘accumulate’ is not a member of ‘std’
     total_trim_tail_right=std::accumulate((*trim_tail_right).begin(), (*trim_tail_right).end(), 0);
                           ^
verbose.cpp:48:26: error: ‘accumulate’ is not a member of ‘std’
     total_trim_qual_left=std::accumulate((*trim_qual_left).begin(), (*trim_qual_left).end(), 0);
                          ^
verbose.cpp:49:27: error: ‘accumulate’ is not a member of ‘std’
     total_trim_qual_right=std::accumulate((*trim_qual_right).begin(), (*trim_qual_right).end(), 0);

```

**Comment by Adrian-Cantu** [comment] 2018-06-14 20:54
This is embarrassing, I forgot to add a header.... [this one](https://github.com/Adrian-Cantu/PRINSEQ-plus-plus/releases/download/v1.2-devel/prinseq-plus-plus-1.2-devel.tar.gz) should work

**Comment by fgvieira** [comment] 2018-06-15 08:05
Yes, that one compiles, but now I get a `segfault` on `make test`:

```
$ make test
cd src && make test
make[1]: Entering directory `prinseq-plus-plus-1.1/src'
./prinseq++ -fastq test_F.fastq -fastq2 test_R.fastq -out_format 1 -out_name Test_1 && \
./prinseq++ -fastq test_F.fastq -fastq2 test_R.fastq -trim_qual_right=25 -out_name Test_2 && \
    ./prinseq++ -fastq test_F.fastq -fastq2 test_R.fastq -min_qual_mean 25 -ns_max_n 2 -out_name Test_3 && \
    ./prinseq++ -fastq test_F.fastq.gz -fastq2 test_R.fastq.gz -out_format 1 -out_name Test_1Z && \
./prinseq++ -fastq test_F.fastq.gz -fastq2 test_R.fastq.gz -trim_qual_right=25 -out_name Test_2Z && \
    ./prinseq++ -fastq test_F.fastq.gz -fastq2 test_R.fastq.gz -min_qual_mean 25 -ns_max_n 2 -out_name Test_3Z && \
echo "*** ALL TEST PASSED***"
/bin/sh: line 6: 103068 Segmentation fault      ./prinseq++ -fastq test_F.fastq -fastq2 test_R.fastq -out_format 1 -out_name Test_1
make[1]: *** [test] Error 139
make[1]: Leaving directory `prinseq-plus-plus-1.1/src'
make: *** [test] Error 2
```

Any idea? :)

**Comment by Adrian-Cantu** [comment] 2018-07-18 23:44
I'm unable to reproduce the error, I recommend installing the new version 1.2. I will close the issue as the original request is implemented, but please post a new one if the problem continues.

**Closed as completed by Adrian-Cantu** 2018-07-18 23:44 UTC
